name: Build Servicefoundry-Server

on:
  push:
    branches:
      - main
      - release

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set repository name
        run: |
          echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Update values.yaml file
        id: dotenv
        uses: ./.github/actions/dotenv-action
        
      - name: Commit updated Chart
        run: |
          cd tmp_ahc
          git config user.name github-action
          git add charts/${{ env.REPOSITORY_NAME }}/values.yaml
          git commit -m "[CI] Update values.yaml for ${{ env.REPOSITORY_NAME }}"
          git push
